### ISSUE TITLE
cortana

### ISSUE THREAD

**Issue by madridfran** [aikoncwd/win10script#7]
buenas..
1./ restaur'e los cambios usando el 99 pero cortana no me habla.. es decir.. me deriva al navegador.. puede ser por algo del script? Ademas me dice que windows debe ser activado.. sin embargo tengo una licencia win 10 pro con derechos digitales .. y ademas la reconoce como tal.. 

2./ En otro pc .. cuando doy a restaurar los host de win 10 se me cierra el script y no restaura.. se puede solucioinar?

**Comment by kimebd** [comment]
Buenas @madridfran que me corrija @aikoncwd si me equivoco pero el restablecer los cambios opción 99 no restablece cortana cuando has usado la opción 3 dentro de las opciones de cortana porque elimina los archivos que este necesita para funcionar como bien advierte el script. Para restablecerlo se necesita un escaneo de los archivos de windows con sfc /scannow.

Por otro lado el restaurar el archivo host mi recomendación es que lo hagas con notepad++ que esta situado en C:\Windows\system32\drivers\etc\host borras este archivo y el denominado host.cwd le borras la extensión que es la copia que genera el script para poder restablecer por algún motivo quizás no la tengas, si es así coge el archivo host y manualmente le eliminas todas las lineas y ya lo tendrás limpio.

Un saludo.
